version: '3'
services:
  flask:
    build: .
    # command: flask run --host=0.0.0.0
    command: gunicorn -w 4 -b 0.0.0.0:5000 hello:app --reload
    environment:
      - FLASK_APP=hello.py
      - FLASK_DEBUG=1
      - PYTHONBUFFERED=True
    ports:
      - "5000:5000"
    volumes:
      - ./:/root
